FROM 172.30.3.149/common/alpine_timezone_shanghai:3.11.3
LABEL maintainer="William Cassanova <wssanova@us.ibm.com>, Tomash Sidei <tomash.sidei@ibm.com>, Kenny Scharm <kenny.scharm@ibm.com>"
COPY bin/metrics /
ENTRYPOINT ["/metrics"]
