---
# Source: operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  labels:
    helm.sh/chart: operator-0.3.14
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
---
# Source: operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator
  labels:
    helm.sh/chart: operator-0.3.14
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: ["db.ibm.com"]
  resources: ["redisclusters", "redisclusters/status"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["*"]
---
# Source: operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator
  labels:
    helm.sh/chart: operator-0.3.14
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-operator
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: redis-system-ibm
---
# Source: operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-operator
  labels:
    helm.sh/chart: operator-0.3.14
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 2112
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redis
---
# Source: operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: "redis-system-ibm"
  labels:
    helm.sh/chart: operator-0.3.14
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: operator
      app.kubernetes.io/instance: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: redis
    spec:
      serviceAccountName: "redis-operator"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: operator
              app.kubernetes.io/instance: redis
      containers:
        - name: operator
          image: "172.30.3.150/devops/redis-operator:latest"
          imagePullPolicy: Allways
          env:
          - name: NAMESPACE
            value: "redis-system-ibm"
          - name: LEADERELECTION_ENABLED
            value: "false"
          args: [
            "--v=2","--logtostderr=true","--alsologtostderr"]
          ports:
            - name: health
              containerPort: 8086
              protocol: TCP
            - name: metrics
              containerPort: 2112
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
